services:
  market_app:
    image: danielmanciu/market-app-server:latest
    build: ./server/market-app
    restart: unless-stopped
    container_name: market_app_server
    networks:
      - shared-network

  car_app:
    image: danielmanciu/car-app-server:latest
    build: ./server/car-app
    restart: unless-stopped
    container_name: car_app_server
    networks:
      - shared-network

  nginx:
    image: nginx:1.29.0-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/certs:/etc/nginx/certs"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared-network

networks:
  shared-network:
