name: Push Docker Image and nginx config

on:
  push:
    tags:
      # - '*'
      - '*-test'
  
env:
  AWS_REGION: eu-north-1
  AWS_ACCOUNT_ID: 267348411096
  S3_BUCKET_NAME: market-app-s3

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionRole
        aws-region: ${{ env.AWS_REGION }} 

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set ECR variables
      id: ecr-vars
      run: |
        AWS_ECR_REGISTRY=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        AWS_ECR_IMAGE_NAME=danielmanciu/market-app-server
        AWS_ECR_IMAGE_VERSION=${{ github.ref_name }}

        echo "aws_ecr_registry=${AWS_ECR_REGISTRY}" >> "$GITHUB_OUTPUT"
        echo "aws_ecr_image_name=${AWS_ECR_IMAGE_NAME}" >> "$GITHUB_OUTPUT"
        echo "aws_ecr_repository_tag=${AWS_ECR_REGISTRY}/${AWS_ECR_IMAGE_NAME}:${AWS_ECR_IMAGE_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.ecr-vars.outputs.aws_ecr_repository_tag }}

    - name: Update docker-compose.yml with tag
      run: |
        sed -i "s|image: ${{ steps.ecr-vars.outputs.aws_ecr_image_name }}:.*|image: ${{ steps.ecr-vars.outputs.aws_ecr_repository_tag }}|" docker-compose.yml

    - name: Upload docker-compose.yml to S3
      run: |
        aws s3 cp docker-compose.yml s3://${{ env.S3_BUCKET_NAME }}/docker/docker-compose.yml --metadata "version=${{ github.ref_name }}"

    - name: Upload nginx.conf to S3
      run: |
        aws s3 cp nginx/nginx.conf s3://${{ env.S3_BUCKET_NAME }}/nginx/nginx.conf --metadata "version=${{ github.ref_name }}"
